---
- name: Copy config file
  hosts: all
  tags: ssh_config

  tasks:
    - name: Copying file
      copy:
        src: ssh_config
        dest: ~/.ssh/config
        mode: '0644'
      delegate_to: localhost
      run_once: true

- name: Pull git project
  hosts: all
  tags: dir

  tasks:
    - name: task 2 - clone git repo
      git:
        repo: git@github.com:roulette6/ansible-test.git
        accept_hostkey: true
        dest: "{{ git_dir }}"
        force: true
      delegate_to: rocky2.vm.jm
      run_once: true


- name: Cat config files
  hosts: rocky3.vm.jm
  tags: config

  tasks:
    - name: task 1 of 4 - get running config for rt1
      command: cat ~/rt1.txt
      register: cli_results

    - name: task 2 of 4 - save config to file
      copy:
        content: "{{ cli_results.stdout }}"
        dest: "{{ git_dir }}/backups/{{ inventory_hostname }}_rt1.cfg"
      delegate_to: rocky2.vm.jm

    - name: task 3 of 4 - get running config for rt2
      command: cat ~/rt2.txt
      register: cli_results

    - name: task 4 of 4 - save config to file
      copy:
        content: "{{ cli_results.stdout }}"
        dest: "{{ git_dir }}/backups/{{ inventory_hostname }}_rt2.cfg"
      delegate_to: rocky2.vm.jm


- name: Commit config and push
  hosts: all
  tags: git

  tasks:
    - name: Task 1 of 5 - Get current date and time
      command: date +"%F %T %Z"
      register: date
      delegate_to: rocky2.vm.jm

    - name: Task 2 of 5 - Check directory status
      shell: "cd {{ git_dir }} && git status backups/*"
      register: git_status
      changed_when: false
      delegate_to: rocky2.vm.jm
      run_once: yes

    - name: Task 3 of 5 - Get git diff
      tags: diff
      shell: "cd {{ git_dir }} && git diff --color | aha > {{ git_dir }}/backups/diffs.html"
      register: git_diff
      when:
        - not("nothing to commit" in git_status.stdout)
      delegate_to: rocky2.vm.jm
      run_once: yes

    - name: Task 4 of 5 - Save output of git_diff
      copy:
        content: "{{ git_diff.stdout }}"
        dest: "{{ git_dir }}/diff.txt"
      run_once: yes
      delegate_to: rocky2.vm.jm

    - name: Task 3 of 5 - Commmit changes to Git
      tags: commit
      shell: |
        cd {{ git_dir }}
        git add backups/*
        git commit -m "Committing changes to running configs on {{ date.stdout }}"
        git push origin main
      when:
        - not("nothing to commit" in git_status.stdout)
      delegate_to: rocky2.vm.jm
      run_once: yes
